/* =========================================================
   COPA MANAGER 2026 — datos/arbitros-seed.js
   Semilla de árbitros designados. Los nombres de país vienen tal cual de la fuente y se
   resuelven contra DB.countries en la migración (con alias para los que difieren en acentos).
   Script CLÁSICO. Cargar DESPUÉS de datos/constantes.js.
   ========================================================= */

const REFEREES_SEED = [
  {firstName:"Abdulrahman", lastName:"Al-Jassim", commonName:"", fullName:"Abdulrahman Ibrahim Al-Jassim", birthDate:"1987-10-14", gender:"Masculino", fifaSince:2013, nationalities:["Catar"], countryRepresents:"Catar", countryWorks:"Catar", role:"Árbitro central", previousWorldCups:["2018", "2022"], matches:[21, 67]},
  {firstName:"Abongile", lastName:"Tom", commonName:"", fullName:"", birthDate:"1991-12-16", gender:"Masculino", fifaSince:2020, nationalities:["Sudafrica"], countryRepresents:"Sudafrica", countryWorks:"Sudafrica", role:"Árbitro central", previousWorldCups:[], matches:[]},
  {firstName:"Adham", lastName:"Makhadmeh", commonName:"", fullName:"Adham Mohammad Tumah Makhadmeh", birthDate:"1987-02-13", gender:"Masculino", fifaSince:2013, nationalities:["Jordania"], countryRepresents:"Jordania", countryWorks:"Jordania", role:"Árbitro central", previousWorldCups:[], matches:[13, 64, 80, 94]},
  {firstName:"Alejandro", lastName:"Hernández Hernández", commonName:"", fullName:"Alejandro José Hernández Hernández", birthDate:"1982-11-10", gender:"Masculino", fifaSince:2014, nationalities:["España"], countryRepresents:"España", countryWorks:"España", role:"Árbitro central", previousWorldCups:[], matches:[31]},
  {firstName:"Alireza", lastName:"Faghani", commonName:"", fullName:"", birthDate:"1978-03-21", gender:"Masculino", fifaSince:2008, nationalities:["Iran"], countryRepresents:"Australia", countryWorks:"Australia", role:"Árbitro central", previousWorldCups:["2014", "2018", "2022"], matches:[17, 71, 92]},
  {firstName:"Amin", lastName:"Omar", commonName:"", fullName:"Amin Mohamed Omar", birthDate:"1985-09-25", gender:"Masculino", fifaSince:2017, nationalities:["Egipto"], countryRepresents:"Egipto", countryWorks:"Egipto", role:"Árbitro central", previousWorldCups:[], matches:[2, 41]},
  {firstName:"Andrés", lastName:"Rojas", commonName:"", fullName:"Andrés José Rojas Noguera", birthDate:"1984-12-05", gender:"Masculino", fifaSince:2017, nationalities:["Colombia"], countryRepresents:"Colombia", countryWorks:"Colombia", role:"Árbitro central", previousWorldCups:["2022"], matches:[]},
  {firstName:"Anthony", lastName:"Taylor", commonName:"", fullName:"", birthDate:"1978-10-20", gender:"Masculino", fifaSince:2013, nationalities:["Inglaterra"], countryRepresents:"Inglaterra", countryWorks:"Inglaterra", role:"Árbitro central", previousWorldCups:["2022"], matches:[24, 62, 93]},
  {firstName:"Campbell-Kirk", lastName:"Kawana-Waugh", commonName:"", fullName:"", birthDate:"1979-11-25", gender:"Masculino", fifaSince:2018, nationalities:["Nueva Zelanda"], countryRepresents:"Nueva Zelanda", countryWorks:"Nueva Zelanda", role:"Árbitro central", previousWorldCups:[], matches:[]},
  {firstName:"César Arturo", lastName:"Ramos", commonName:"", fullName:"César Arturo Ramos Palazuelos", birthDate:"1983-12-15", gender:"Masculino", fifaSince:2014, nationalities:["México"], countryRepresents:"México", countryWorks:"México", role:"Árbitro central", previousWorldCups:["2018", "2022"], matches:[16, 51]},
  {firstName:"Clément", lastName:"Turpin", commonName:"", fullName:"", birthDate:"1982-05-16", gender:"Masculino", fifaSince:2010, nationalities:["Francia"], countryRepresents:"Francia", countryWorks:"Francia", role:"Árbitro central", previousWorldCups:["2018", "2022"], matches:[22, 60, 87, 99]},
  {firstName:"Cristián", lastName:"Garay", commonName:"", fullName:"Cristián Marcelo Garay Reyes", birthDate:"1989-04-08", gender:"Masculino", fifaSince:2019, nationalities:["Chile"], countryRepresents:"Chile", countryWorks:"Chile", role:"Árbitro central", previousWorldCups:[], matches:[27]},
  {firstName:"Dahane", lastName:"Beida", commonName:"", fullName:"", birthDate:"1991-12-31", gender:"Masculino", fifaSince:2018, nationalities:["Mauritania"], countryRepresents:"Mauritania", countryWorks:"Mauritania", role:"Árbitro central", previousWorldCups:[], matches:[20]},
  {firstName:"Danny", lastName:"Makkelie", commonName:"", fullName:"Danny Desmond Makkelie", birthDate:"1983-01-28", gender:"Masculino", fifaSince:2011, nationalities:["Países Bajos"], countryRepresents:"Países Bajos", countryWorks:"Países Bajos", role:"Árbitro central", previousWorldCups:["2018", "2022"], matches:[4, 52, 78]},
  {firstName:"Darío", lastName:"Herrera", commonName:"", fullName:"Darío Humberto Herrera", birthDate:"1985-02-24", gender:"Masculino", fifaSince:2015, nationalities:["Argentina"], countryRepresents:"Argentina", countryWorks:"Argentina", role:"Árbitro central", previousWorldCups:[], matches:[38]},
  {firstName:"Drew", lastName:"Fischer", commonName:"", fullName:"", birthDate:"1980-07-10", gender:"Masculino", fifaSince:2015, nationalities:["Canadá"], countryRepresents:"Canadá", countryWorks:"Canadá, Estados Unidos", role:"Árbitro central", previousWorldCups:["2022"], matches:[42, 68, 86]},
  {firstName:"Espen", lastName:"Eskås", commonName:"", fullName:"", birthDate:"1988-06-24", gender:"Masculino", fifaSince:2017, nationalities:["Noruega"], countryRepresents:"Noruega", countryWorks:"Noruega", role:"Árbitro central", previousWorldCups:[], matches:[39, 83]},
  {firstName:"Facundo", lastName:"Tello", commonName:"", fullName:"Facundo Raúl Tello Figueroa", birthDate:"1982-05-04", gender:"Masculino", fifaSince:2019, nationalities:["Argentina"], countryRepresents:"Argentina", countryWorks:"Argentina", role:"Árbitro central", previousWorldCups:["2022"], matches:[3, 54, 97]},
  {firstName:"Felix", lastName:"Zwayer", commonName:"", fullName:"", birthDate:"1981-05-19", gender:"Masculino", fifaSince:2012, nationalities:["Alemania"], countryRepresents:"Alemania", countryWorks:"Alemania", role:"Árbitro central", previousWorldCups:[], matches:[29, 72]},
  {firstName:"François", lastName:"Letexier", commonName:"", fullName:"", birthDate:"1989-04-23", gender:"Masculino", fifaSince:2017, nationalities:["Francia"], countryRepresents:"Francia", countryWorks:"Francia", role:"Árbitro central", previousWorldCups:[], matches:[11, 65, 95]},
  {firstName:"Glenn", lastName:"Nyberg", commonName:"", fullName:"Glenn Per Nyberg", birthDate:"1988-10-12", gender:"Masculino", fifaSince:2016, nationalities:["Suecia"], countryRepresents:"Suecia", countryWorks:"Suecia", role:"Árbitro central", previousWorldCups:[], matches:[23, 55, 84]},
  {firstName:"Gustavo", lastName:"Tejera", commonName:"", fullName:"Gustavo Adrián Tejera Capo", birthDate:"1988-01-20", gender:"Masculino", fifaSince:2018, nationalities:["Uruguay"], countryRepresents:"Uruguay", countryWorks:"Uruguay", role:"Árbitro central", previousWorldCups:[], matches:[28, 88]},
  {firstName:"Ilgiz", lastName:"Tantashev", commonName:"", fullName:"", birthDate:"1984-04-05", gender:"Masculino", fifaSince:2013, nationalities:["Uzbekistan"], countryRepresents:"Uzbekistan", countryWorks:"Uzbekistan", role:"Árbitro central", previousWorldCups:[], matches:[30, 69, 89]},
  {firstName:"Ismail", lastName:"Elfath", commonName:"", fullName:"", birthDate:"1982-03-03", gender:"Masculino", fifaSince:2016, nationalities:["Marruecos"], countryRepresents:"Estados Unidos", countryWorks:"Estados Unidos", role:"Árbitro central", previousWorldCups:["2022"], matches:[10, 66, 91, 102]},
  {firstName:"István", lastName:"Kovács", commonName:"", fullName:"", birthDate:"1984-09-16", gender:"Masculino", fifaSince:2010, nationalities:["Rumanía"], countryRepresents:"Rumanía", countryWorks:"Rumanía", role:"Árbitro central", previousWorldCups:["2022"], matches:[36, 70]},
  {firstName:"Iván", lastName:"Barton", commonName:"", fullName:"Iván Arcides Barton Cisneros", birthDate:"1991-01-27", gender:"Masculino", fifaSince:2018, nationalities:["El Salvador"], countryRepresents:"El Salvador", countryWorks:"El Salvador", role:"Árbitro central", previousWorldCups:["2022"], matches:[32, 57, 96, 101]},
  {firstName:"Jalal", lastName:"Jayed", commonName:"", fullName:"", birthDate:"1987-03-23", gender:"Masculino", fifaSince:2019, nationalities:["Marruecos"], countryRepresents:"Marruecos", countryWorks:"Marruecos", role:"Árbitro central", previousWorldCups:[], matches:[9, 45, 75]},
  {firstName:"Jesús", lastName:"Valenzuela", commonName:"", fullName:"Jesús Noel Valenzuela Sáez", birthDate:"1983-11-24", gender:"Masculino", fifaSince:2013, nationalities:["Venezuela"], countryRepresents:"Venezuela", countryWorks:"Venezuela", role:"Árbitro central", previousWorldCups:["2022"], matches:[8, 50, 77, 103]},
  {firstName:"João", lastName:"Pinheiro", commonName:"", fullName:"João Pedro da Silva Pinheiro", birthDate:"1988-01-04", gender:"Masculino", fifaSince:2016, nationalities:["Portugal"], countryRepresents:"Portugal", countryWorks:"Portugal", role:"Árbitro central", previousWorldCups:[], matches:[26, 73, 100]},
  {firstName:"Juan Gabriel", lastName:"Calderón", commonName:"", fullName:"Juan Gabriel Calderón Pérez", birthDate:"1987-04-11", gender:"Masculino", fifaSince:2017, nationalities:["Costa Rica"], countryRepresents:"Costa Rica", countryWorks:"Costa Rica", role:"Árbitro central", previousWorldCups:[], matches:[]},
  {firstName:"Juan Gabriel", lastName:"Benítez", commonName:"", fullName:"Juan Gabriel Benítez Mareco", birthDate:"1982-10-23", gender:"Masculino", fifaSince:2019, nationalities:["Paraguay"], countryRepresents:"Paraguay", countryWorks:"Paraguay", role:"Árbitro central", previousWorldCups:[], matches:[34]},
  {firstName:"Katia Itzel", lastName:"García", commonName:"", fullName:"Katia Itzel García Mendoza", birthDate:"1992-09-01", gender:"Femenino", fifaSince:2019, nationalities:["México"], countryRepresents:"México", countryWorks:"México", role:"Árbitro central", previousWorldCups:[], matches:[58]},
  {firstName:"Kevin", lastName:"Ortega", commonName:"", fullName:"Kevin Paolo Ortega Pimentel", birthDate:"1992-03-26", gender:"Masculino", fifaSince:2019, nationalities:["Perú"], countryRepresents:"Perú", countryWorks:"Perú", role:"Árbitro central", previousWorldCups:["2022"], matches:[]},
  {firstName:"Khalid", lastName:"Al-Turais", commonName:"", fullName:"Khalid Saleh Al-Turais", birthDate:"1987-04-30", gender:"Masculino", fifaSince:2016, nationalities:["Arabia Saudita"], countryRepresents:"Arabia Saudita", countryWorks:"Arabia Saudita", role:"Árbitro central", previousWorldCups:[], matches:[]},
  {firstName:"Ma", lastName:"Ning", commonName:"", fullName:"", birthDate:"1979-06-20", gender:"Masculino", fifaSince:2011, nationalities:["China"], countryRepresents:"China", countryWorks:"China", role:"Árbitro central", previousWorldCups:["2022"], matches:[35]},
  {firstName:"Maurizio", lastName:"Mariani", commonName:"", fullName:"", birthDate:"1982-02-25", gender:"Masculino", fifaSince:2019, nationalities:["Italia"], countryRepresents:"Italia", countryWorks:"Italia", role:"Árbitro central", previousWorldCups:[], matches:[15, 48, 74]},
  {firstName:"Michael", lastName:"Oliver", commonName:"", fullName:"", birthDate:"1985-02-20", gender:"Masculino", fifaSince:2012, nationalities:["Inglaterra"], countryRepresents:"Inglaterra", countryWorks:"Inglaterra", role:"Árbitro central", previousWorldCups:["2022"], matches:[33, 61, 90, 98]},
  {firstName:"Mustapha", lastName:"Ghorbal", commonName:"", fullName:"", birthDate:"1985-08-19", gender:"Masculino", fifaSince:2014, nationalities:["Argelia"], countryRepresents:"Argelia", countryWorks:"Argelia", role:"Árbitro central", previousWorldCups:["2022"], matches:[7, 59]},
  {firstName:"Omar", lastName:"Al Ali", commonName:"", fullName:"", birthDate:"1988-02-16", gender:"Masculino", fifaSince:2015, nationalities:["Emiratos Arabes Unidos"], countryRepresents:"Emiratos Arabes Unidos", countryWorks:"Emiratos Arabes Unidos", role:"Árbitro central", previousWorldCups:[], matches:[40]},
  {firstName:"Oshane", lastName:"Nation", commonName:"", fullName:"", birthDate:"1991-01-10", gender:"Masculino", fifaSince:2018, nationalities:["Jamaica"], countryRepresents:"Jamaica", countryWorks:"Jamaica", role:"Árbitro central", previousWorldCups:[], matches:[]},
  {firstName:"Pierre", lastName:"Atcho", commonName:"", fullName:"Pierre Ghislain Atcho", birthDate:"1992-10-10", gender:"Masculino", fifaSince:2018, nationalities:["Gabón"], countryRepresents:"Gabón", countryWorks:"Gabón", role:"Árbitro central", previousWorldCups:[], matches:[18, 47]},
  {firstName:"Ramon", lastName:"Abatti", commonName:"", fullName:"Ramon Abatti Abel", birthDate:"1989-09-18", gender:"Masculino", fifaSince:2021, nationalities:["Brasil"], countryRepresents:"Brasil", countryWorks:"Brasil", role:"Árbitro central", previousWorldCups:[], matches:[14, 49]},
  {firstName:"Raphael", lastName:"Claus", commonName:"", fullName:"", birthDate:"1979-09-06", gender:"Masculino", fifaSince:2015, nationalities:["Brasil"], countryRepresents:"Brasil", countryWorks:"Brasil", role:"Árbitro central", previousWorldCups:["2022"], matches:[37, 81]},
  {firstName:"Saíd", lastName:"Martínez", commonName:"", fullName:"Héctor Saíd Martínez Sorto", birthDate:"1991-08-07", gender:"Masculino", fifaSince:2017, nationalities:["Honduras"], countryRepresents:"Honduras", countryWorks:"Honduras", role:"Árbitro central", previousWorldCups:["2022"], matches:[5, 46, 82]},
  {firstName:"Sandro", lastName:"Schärer", commonName:"", fullName:"", birthDate:"1988-06-06", gender:"Masculino", fifaSince:2015, nationalities:["Suiza"], countryRepresents:"Suiza", countryWorks:"Suiza", role:"Árbitro central", previousWorldCups:[], matches:[]},
  {firstName:"Slavko", lastName:"Vinčić", commonName:"", fullName:"", birthDate:"1979-11-25", gender:"Masculino", fifaSince:2010, nationalities:["Eslovenia"], countryRepresents:"Eslovenia", countryWorks:"Eslovenia", role:"Árbitro central", previousWorldCups:["2022"], matches:[6, 44, 79, 104]},
  {firstName:"Szymon", lastName:"Marciniak", commonName:"", fullName:"", birthDate:"1981-01-07", gender:"Masculino", fifaSince:2011, nationalities:["Polonia"], countryRepresents:"Polonia", countryWorks:"Polonia", role:"Árbitro central", previousWorldCups:["2022"], matches:[19, 63]},
  {firstName:"Tori", lastName:"Penso", commonName:"", fullName:"Mary Victoria Penso", birthDate:"1986-07-08", gender:"Femenino", fifaSince:2021, nationalities:["Estados Unidos"], countryRepresents:"Estados Unidos", countryWorks:"Estados Unidos", role:"Árbitro central", previousWorldCups:[], matches:[25, 56]},
  {firstName:"Wilton", lastName:"Sampaio", commonName:"", fullName:"Wilton Pereira Sampaio", birthDate:"1981-12-28", gender:"Masculino", fifaSince:2013, nationalities:["Brasil"], countryRepresents:"Brasil", countryWorks:"Brasil", role:"Árbitro central", previousWorldCups:[], matches:[1, 43, 76]},
  {firstName:"Yael", lastName:"Falcón", commonName:"", fullName:"Yael Falcón Pérez", birthDate:"1988-12-15", gender:"Masculino", fifaSince:2022, nationalities:["Argentina"], countryRepresents:"Argentina", countryWorks:"Argentina", role:"Árbitro central", previousWorldCups:[], matches:[12, 53, 85]},
  {firstName:"Yusuke", lastName:"Araki", commonName:"", fullName:"", birthDate:"1986-05-02", gender:"Masculino", fifaSince:2017, nationalities:["Japón"], countryRepresents:"Japón", countryWorks:"Japón", role:"Árbitro central", previousWorldCups:[], matches:[]}
];

// Alias para nombres de país de la fuente que no coinciden exactamente con el catálogo.
const REFEREE_COUNTRY_ALIASES = {
  "sudafrica":"Sudáfrica", "iran":"Irán", "emiratos arabes unidos":"Emiratos Árabes Unidos",
  "paises bajos":"Países Bajos", "rumania":"Rumanía", "chequia":"República Checa"
};
