/* =========================================================
   COPA MANAGER 2026 — datos/gentilicios.js
   Gentilicios (masculino/femenino) por país, importados de gentilicios.xlsx.
   BY_FIFA usa el código FIFA (emparejamiento robusto); BY_NAME es respaldo por nombre (normLoose).
   migrateDB() los sella en cada país (country.gentilicioM / country.gentilicioF) sin sobreescribir
   ediciones manuales. Cargar después de datos/constantes.js.
   ========================================================= */
const DEMONYM_BY_FIFA = {
  "ABH": {"m":"abjasio","f":"abjasia"},
  "AFG": {"m":"afgano","f":"afgana"},
  "AIA": {"m":"anguilense","f":"anguilense"},
  "ALA": {"m":"alandés","f":"alandesa"},
  "ALB": {"m":"albanés","f":"albanesa"},
  "ALG": {"m":"argelino","f":"argelina"},
  "AND": {"m":"andorrano","f":"andorrana"},
  "ANG": {"m":"angoleño","f":"angoleña"},
  "ARG": {"m":"argentino","f":"argentina"},
  "ARM": {"m":"armenio","f":"armenia"},
  "ARU": {"m":"arubeño","f":"arubeña"},
  "ASA": {"m":"samoamericano","f":"samoamericana"},
  "ATG": {"m":"antiguano","f":"antiguana"},
  "AUS": {"m":"australiano","f":"australiana"},
  "AUT": {"m":"austriaco","f":"austriaca"},
  "AZE": {"m":"azerbaiyano","f":"azerbaiyana"},
  "BAH": {"m":"bahameño","f":"bahameña"},
  "BAN": {"m":"bangladesí","f":"bangladesí"},
  "BDI": {"m":"burundés","f":"burundesa"},
  "BEL": {"m":"belga","f":"belga"},
  "BEN": {"m":"beninés","f":"beninesa"},
  "BER": {"m":"bermudeño","f":"bermudeña"},
  "BFA": {"m":"burkinés","f":"burkinesa"},
  "BHR": {"m":"bareiní","f":"bareiní"},
  "BHU": {"m":"butanés","f":"butanesa"},
  "BIH": {"m":"bosnio","f":"bosnia"},
  "BLM": {"m":"sanbartolomeano","f":"sanbartolomeana"},
  "BLR": {"m":"bielorruso","f":"bielorrusa"},
  "BLZ": {"m":"beliceño","f":"beliceña"},
  "BOL": {"m":"boliviano","f":"boliviana"},
  "BON": {"m":"bonairense","f":"bonairense"},
  "BOT": {"m":"botsuano","f":"botsuana"},
  "BRA": {"m":"brasileño","f":"brasileña"},
  "BRB": {"m":"barbadense","f":"barbadense"},
  "BRU": {"m":"bruneano","f":"bruneana"},
  "BSQ": {"m":"vasco","f":"vasca"},
  "BUL": {"m":"búlgaro","f":"búlgara"},
  "CAM": {"m":"camboyano","f":"camboyana"},
  "CAN": {"m":"canadiense","f":"canadiense"},
  "CAT": {"m":"catalán","f":"catalana"},
  "CAY": {"m":"caimanés","f":"caimanesa"},
  "CGO": {"m":"congoleño","f":"congoleña"},
  "CHA": {"m":"chadiano","f":"chadiana"},
  "CHI": {"m":"chileno","f":"chilena"},
  "CHN": {"m":"chino","f":"china"},
  "CIV": {"m":"marfileño","f":"marfileña"},
  "CMR": {"m":"camerunés","f":"camerunesa"},
  "COD": {"m":"congoleño","f":"congoleña"},
  "COK": {"m":"cookiano","f":"cookiana"},
  "COL": {"m":"colombiano","f":"colombiana"},
  "COM": {"m":"comorense","f":"comorense"},
  "CPV": {"m":"caboverdiano","f":"caboverdiana"},
  "CRC": {"m":"costarricense","f":"costarricense"},
  "CRO": {"m":"croata","f":"croata"},
  "CTA": {"m":"centroafricano","f":"centroafricana"},
  "CUB": {"m":"cubano","f":"cubana"},
  "CUW": {"m":"curazoleño","f":"curazoleña"},
  "CYP": {"m":"chipriota","f":"chipriota"},
  "CZE": {"m":"checo","f":"checa"},
  "DEN": {"m":"danés","f":"danesa"},
  "DJI": {"m":"yibutiano","f":"yibutiana"},
  "DMA": {"m":"dominiqués","f":"dominiquesa"},
  "DOM": {"m":"dominicano","f":"dominicana"},
  "ECU": {"m":"ecuatoriano","f":"ecuatoriana"},
  "EGY": {"m":"egipcio","f":"egipcia"},
  "ENG": {"m":"inglés","f":"inglesa"},
  "EQG": {"m":"ecuatoguineano","f":"ecuatoguineana"},
  "ERI": {"m":"eritreo","f":"eritrea"},
  "ESP": {"m":"español","f":"española"},
  "EST": {"m":"estonio","f":"estonia"},
  "ETH": {"m":"etíope","f":"etíope"},
  "FIJ": {"m":"fiyiano","f":"fiyiana"},
  "FIN": {"m":"finlandés","f":"finlandesa"},
  "FIS": {"m":"malvinense","f":"malvinense"},
  "FRA": {"m":"francés","f":"francesa"},
  "FRO": {"m":"feroés","f":"feroesa"},
  "GAB": {"m":"gabonés","f":"gabonesa"},
  "GAM": {"m":"gambiano","f":"gambiana"},
  "GEO": {"m":"georgiano","f":"georgiana"},
  "GER": {"m":"alemán","f":"alemana"},
  "GGY": {"m":"guerneseyés","f":"guerneseyesa"},
  "GHA": {"m":"ghanés","f":"ghanesa"},
  "GIB": {"m":"gibraltareño","f":"gibraltareña"},
  "GLP": {"m":"guadalupeño","f":"guadalupeña"},
  "GNB": {"m":"bisauguineano","f":"bisauguineana"},
  "GOZ": {"m":"gozitano","f":"gozitana"},
  "GRE": {"m":"griego","f":"griega"},
  "GRL": {"m":"groenlandés","f":"groenlandesa"},
  "GRN": {"m":"granadino","f":"granadina"},
  "GUA": {"m":"guatemalteco","f":"guatemalteca"},
  "GUF": {"m":"francoguayanés","f":"francoguayanesa"},
  "GUI": {"m":"guineano","f":"guineana"},
  "GUM": {"m":"guameño","f":"guameña"},
  "GUY": {"m":"guyanés","f":"guyanesa"},
  "HAI": {"m":"haitiano","f":"haitiana"},
  "HKG": {"m":"hongkonés","f":"hongkonesa"},
  "HON": {"m":"hondureño","f":"hondureña"},
  "HUN": {"m":"húngaro","f":"húngara"},
  "IDN": {"m":"indonesio","f":"indonesia"},
  "IND": {"m":"indio","f":"india"},
  "IOM": {"m":"manés","f":"manesa"},
  "IRL": {"m":"irlandés","f":"irlandesa"},
  "IRN": {"m":"iraní","f":"iraní"},
  "IRQ": {"m":"iraquí","f":"iraquí"},
  "ISL": {"m":"islandés","f":"islandesa"},
  "ISR": {"m":"israelí","f":"israelí"},
  "ITA": {"m":"italiano","f":"italiana"},
  "JAM": {"m":"jamaicano","f":"jamaicana"},
  "JER": {"m":"jerseyés","f":"jerseyesa"},
  "JOR": {"m":"jordano","f":"jordana"},
  "JPN": {"m":"japonés","f":"japonesa"},
  "KAZ": {"m":"kazajo","f":"kazaja"},
  "KEN": {"m":"keniano","f":"keniana"},
  "KGZ": {"m":"kirguís","f":"kirguís"},
  "KIR": {"m":"kiribatiano","f":"kiribatiana"},
  "KOR": {"m":"surcoreano","f":"surcoreana"},
  "KOS": {"m":"kosovar","f":"kosovar"},
  "KSA": {"m":"saudí","f":"saudí"},
  "KUW": {"m":"kuwaití","f":"kuwaití"},
  "LAO": {"m":"laosiano","f":"laosiana"},
  "LBN": {"m":"libanés","f":"libanesa"},
  "LBR": {"m":"liberiano","f":"liberiana"},
  "LBY": {"m":"libio","f":"libia"},
  "LCA": {"m":"santalucense","f":"santalucense"},
  "LES": {"m":"lesotense","f":"lesotense"},
  "LIE": {"m":"liechtensteiniano","f":"liechtensteiniana"},
  "LTU": {"m":"lituano","f":"lituana"},
  "LUX": {"m":"luxemburgués","f":"luxemburguesa"},
  "LVA": {"m":"letón","f":"letona"},
  "MAC": {"m":"macaense","f":"macaense"},
  "MAD": {"m":"malgache","f":"malgache"},
  "MAR": {"m":"marroquí","f":"marroquí"},
  "MAS": {"m":"malasio","f":"malasia"},
  "MDA": {"m":"moldavo","f":"moldava"},
  "MDV": {"m":"maldivo","f":"maldiva"},
  "MEX": {"m":"mexicano","f":"mexicana"},
  "MKD": {"m":"macedonio","f":"macedonia"},
  "MLI": {"m":"maliense","f":"maliense"},
  "MLT": {"m":"maltés","f":"maltesa"},
  "MNE": {"m":"montenegrino","f":"montenegrina"},
  "MNG": {"m":"mongol","f":"mongola"},
  "MNP": {"m":"chamorro","f":"chamorra"},
  "MOZ": {"m":"mozambiqueño","f":"mozambiqueña"},
  "MRI": {"m":"mauriciano","f":"mauriciana"},
  "MSR": {"m":"monserratino","f":"monserratina"},
  "MTN": {"m":"mauritano","f":"mauritana"},
  "MTQ": {"m":"martiniqués","f":"martiniquesa"},
  "MWI": {"m":"malauí","f":"malauí"},
  "MYA": {"m":"birmano","f":"birmana"},
  "NAM": {"m":"namibio","f":"namibia"},
  "NCA": {"m":"nicaragüense","f":"nicaragüense"},
  "NCL": {"m":"neocaledonio","f":"neocaledonia"},
  "NCY": {"m":"norchipriota","f":"norchipriota"},
  "NED": {"m":"neerlandés","f":"neerlandesa"},
  "NEP": {"m":"nepalés","f":"nepalesa"},
  "NGA": {"m":"nigeriano","f":"nigeriana"},
  "NIG": {"m":"nigerino","f":"nigerina"},
  "NIR": {"m":"norirlandés","f":"norirlandesa"},
  "NIU": {"m":"niueño","f":"niueña"},
  "NOR": {"m":"noruego","f":"noruega"},
  "NZL": {"m":"neozelandés","f":"neozelandesa"},
  "OMA": {"m":"omaní","f":"omaní"},
  "OSS": {"m":"surosetio","f":"surosetia"},
  "PAK": {"m":"pakistaní","f":"pakistaní"},
  "PAN": {"m":"panameño","f":"panameña"},
  "PAR": {"m":"paraguayo","f":"paraguaya"},
  "PER": {"m":"peruano","f":"peruana"},
  "PHI": {"m":"filipino","f":"filipina"},
  "PLE": {"m":"palestino","f":"palestina"},
  "PMR": {"m":"transnistrio","f":"transnistria"},
  "PNG": {"m":"papú","f":"papú"},
  "POL": {"m":"polaco","f":"polaca"},
  "POR": {"m":"portugués","f":"portuguesa"},
  "PRK": {"m":"norcoreano","f":"norcoreana"},
  "PUR": {"m":"puertorriqueño","f":"puertorriqueña"},
  "QAT": {"m":"catarí","f":"catarí"},
  "REU": {"m":"reunionés","f":"reunionesa"},
  "ROU": {"m":"rumano","f":"rumana"},
  "RSA": {"m":"sudafricano","f":"sudafricana"},
  "RUS": {"m":"ruso","f":"rusa"},
  "RWA": {"m":"ruandés","f":"ruandesa"},
  "SAM": {"m":"samoano","f":"samoana"},
  "SCO": {"m":"escocés","f":"escocesa"},
  "SDN": {"m":"sudanés","f":"sudanesa"},
  "SEN": {"m":"senegalés","f":"senegalesa"},
  "SEY": {"m":"seychellense","f":"seychellense"},
  "SHN": {"m":"santaheleno","f":"santahelena"},
  "SIN": {"m":"singapurense","f":"singapurense"},
  "SKN": {"m":"sancristobaleño","f":"sancristobaleña"},
  "SLE": {"m":"sierraleonés","f":"sierraleonesa"},
  "SLV": {"m":"salvadoreño","f":"salvadoreña"},
  "SMD": {"m":"somalilandés","f":"somalilandesa"},
  "SMN": {"m":"sanmartitense","f":"sanmartitense"},
  "SMR": {"m":"sanmarinense","f":"sanmarinense"},
  "SOL": {"m":"salomonense","f":"salomonense"},
  "SOM": {"m":"somalí","f":"somalí"},
  "SPM": {"m":"sanpedrino","f":"sanpedrina"},
  "SRB": {"m":"serbio","f":"serbia"},
  "SRI": {"m":"esrilanqués","f":"esrilanquesa"},
  "SSD": {"m":"sursudanés","f":"sursudanesa"},
  "STP": {"m":"santotomense","f":"santotomense"},
  "SUI": {"m":"suizo","f":"suiza"},
  "SUR": {"m":"surinamés","f":"surinamesa"},
  "SVK": {"m":"eslovaco","f":"eslovaca"},
  "SVN": {"m":"esloveno","f":"eslovena"},
  "SWE": {"m":"sueco","f":"sueca"},
  "SWZ": {"m":"suazi","f":"suazi"},
  "SXM": {"m":"sanmartitense","f":"sanmartitense"},
  "SYR": {"m":"sirio","f":"siria"},
  "TAH": {"m":"tahitiano","f":"tahitiana"},
  "TAN": {"m":"tanzano","f":"tanzana"},
  "TCA": {"m":"turcocaiqueño","f":"turcocaiqueña"},
  "TGA": {"m":"tongano","f":"tongana"},
  "THA": {"m":"tailandés","f":"tailandesa"},
  "TJK": {"m":"tayiko","f":"tayika"},
  "TKM": {"m":"turcomano","f":"turcomana"},
  "TLS": {"m":"timorense","f":"timorense"},
  "TOG": {"m":"togolés","f":"togolesa"},
  "TOK": {"m":"tokelauense","f":"tokelauense"},
  "TPE": {"m":"taiwanés","f":"taiwanesa"},
  "TRI": {"m":"trinitense","f":"trinitense"},
  "TUN": {"m":"tunecino","f":"tunecina"},
  "TUR": {"m":"turco","f":"turca"},
  "TUV": {"m":"tuvaluano","f":"tuvaluana"},
  "UAE": {"m":"emiratí","f":"emiratí"},
  "UGA": {"m":"ugandés","f":"ugandesa"},
  "UKR": {"m":"ucraniano","f":"ucraniana"},
  "URU": {"m":"uruguayo","f":"uruguaya"},
  "USA": {"m":"estadounidense","f":"estadounidense"},
  "UZB": {"m":"uzbeko","f":"uzbeka"},
  "VAN": {"m":"vanuatuense","f":"vanuatuense"},
  "VAT": {"m":"vaticano","f":"vaticana"},
  "VEN": {"m":"venezolano","f":"venezolana"},
  "VGB": {"m":"virgenense británico","f":"virgenense británica"},
  "VIE": {"m":"vietnamita","f":"vietnamita"},
  "VIN": {"m":"sanvicentino","f":"sanvicentina"},
  "VIR": {"m":"virgenense estadounidense","f":"virgenense estadounidense"},
  "WAL": {"m":"galés","f":"galesa"},
  "WLF": {"m":"walisiano","f":"walisiana"},
  "WSH": {"m":"saharaui","f":"saharaui"},
  "YEM": {"m":"yemení","f":"yemení"},
  "ZAM": {"m":"zambiano","f":"zambiana"},
  "ZAN": {"m":"zanzibarí","f":"zanzibarí"},
  "ZIM": {"m":"zimbabuense","f":"zimbabuense"}
};
const DEMONYM_BY_NAME = {
  "abjasia": {"m":"abjasio","f":"abjasia"},
  "afganistan": {"m":"afgano","f":"afgana"},
  "aland": {"m":"alandés","f":"alandesa"},
  "albania": {"m":"albanés","f":"albanesa"},
  "alemania": {"m":"alemán","f":"alemana"},
  "andalucia": {"m":"andaluz","f":"andaluza"},
  "andorra": {"m":"andorrano","f":"andorrana"},
  "angola": {"m":"angoleño","f":"angoleña"},
  "anguila": {"m":"anguilense","f":"anguilense"},
  "antigua y barbuda": {"m":"antiguano","f":"antiguana"},
  "arabia saudita": {"m":"saudí","f":"saudí"},
  "aragon": {"m":"aragonés","f":"aragonesa"},
  "argelia": {"m":"argelino","f":"argelina"},
  "argentina": {"m":"argentino","f":"argentina"},
  "armenia": {"m":"armenio","f":"armenia"},
  "aruba": {"m":"arubeño","f":"arubeña"},
  "asturias": {"m":"asturiano","f":"asturiana"},
  "australia": {"m":"australiano","f":"australiana"},
  "austria": {"m":"austriaco","f":"austriaca"},
  "azerbaiyan": {"m":"azerbaiyano","f":"azerbaiyana"},
  "bahamas": {"m":"bahameño","f":"bahameña"},
  "banglades": {"m":"bangladesí","f":"bangladesí"},
  "barbados": {"m":"barbadense","f":"barbadense"},
  "barein": {"m":"bareiní","f":"bareiní"},
  "baskortostan": {"m":"bashkirio","f":"bashkiria"},
  "belgica": {"m":"belga","f":"belga"},
  "belice": {"m":"beliceño","f":"beliceña"},
  "benin": {"m":"beninés","f":"beninesa"},
  "bermudas": {"m":"bermudeño","f":"bermudeña"},
  "bielorrusia": {"m":"bielorruso","f":"bielorrusa"},
  "birmania": {"m":"birmano","f":"birmana"},
  "bolivia": {"m":"boliviano","f":"boliviana"},
  "bonaire": {"m":"bonairense","f":"bonairense"},
  "bosnia y herzegovina": {"m":"bosnio","f":"bosnia"},
  "botsuana": {"m":"botsuano","f":"botsuana"},
  "brasil": {"m":"brasileño","f":"brasileña"},
  "brunei": {"m":"bruneano","f":"bruneana"},
  "bulgaria": {"m":"búlgaro","f":"búlgara"},
  "burkina faso": {"m":"burkinés","f":"burkinesa"},
  "burundi": {"m":"burundés","f":"burundesa"},
  "butan": {"m":"butanés","f":"butanesa"},
  "cabo verde": {"m":"caboverdiano","f":"caboverdiana"},
  "camboya": {"m":"camboyano","f":"camboyana"},
  "camerun": {"m":"camerunés","f":"camerunesa"},
  "canada": {"m":"canadiense","f":"canadiense"},
  "canarias": {"m":"canario","f":"canaria"},
  "cantabria": {"m":"cántabro","f":"cántabra"},
  "castilla y leon": {"m":"castellanoleonés","f":"castellanoleonesa"},
  "castillala mancha": {"m":"castellanomanchego","f":"castellanomanchega"},
  "cataluna": {"m":"catalán","f":"catalana"},
  "catar": {"m":"catarí","f":"catarí"},
  "ceuta": {"m":"ceutí","f":"ceutí"},
  "chad": {"m":"chadiano","f":"chadiana"},
  "chile": {"m":"chileno","f":"chilena"},
  "china": {"m":"chino","f":"china"},
  "chipre": {"m":"chipriota","f":"chipriota"},
  "chipre del norte": {"m":"norchipriota","f":"norchipriota"},
  "ciudad del vaticano": {"m":"vaticano","f":"vaticana"},
  "colombia": {"m":"colombiano","f":"colombiana"},
  "comoras": {"m":"comorense","f":"comorense"},
  "comunidad de madrid": {"m":"madrileño","f":"madrileña"},
  "comunidad valenciana": {"m":"valenciano","f":"valenciana"},
  "corea del norte": {"m":"norcoreano","f":"norcoreana"},
  "corea del sur": {"m":"surcoreano","f":"surcoreana"},
  "costa de marfil": {"m":"marfileño","f":"marfileña"},
  "costa rica": {"m":"costarricense","f":"costarricense"},
  "croacia": {"m":"croata","f":"croata"},
  "cuba": {"m":"cubano","f":"cubana"},
  "curazao": {"m":"curazoleño","f":"curazoleña"},
  "dinamarca": {"m":"danés","f":"danesa"},
  "dominica": {"m":"dominiqués","f":"dominiquesa"},
  "eau": {"m":"emiratí","f":"emiratí"},
  "ecuador": {"m":"ecuatoriano","f":"ecuatoriana"},
  "egipto": {"m":"egipcio","f":"egipcia"},
  "el salvador": {"m":"salvadoreño","f":"salvadoreña"},
  "eritrea": {"m":"eritreo","f":"eritrea"},
  "escocia": {"m":"escocés","f":"escocesa"},
  "eslovaquia": {"m":"eslovaco","f":"eslovaca"},
  "eslovenia": {"m":"esloveno","f":"eslovena"},
  "espana": {"m":"español","f":"española"},
  "estados federados de micronesia": {"m":"micronesio","f":"micronesia"},
  "estados unidos": {"m":"estadounidense","f":"estadounidense"},
  "estonia": {"m":"estonio","f":"estonia"},
  "etiopia": {"m":"etíope","f":"etíope"},
  "extremadura": {"m":"extremeño","f":"extremeña"},
  "filipinas": {"m":"filipino","f":"filipina"},
  "finlandia": {"m":"finlandés","f":"finlandesa"},
  "fiyi": {"m":"fiyiano","f":"fiyiana"},
  "francia": {"m":"francés","f":"francesa"},
  "gabon": {"m":"gabonés","f":"gabonesa"},
  "gales": {"m":"galés","f":"galesa"},
  "galicia": {"m":"gallego","f":"gallega"},
  "gambia": {"m":"gambiano","f":"gambiana"},
  "georgia": {"m":"georgiano","f":"georgiana"},
  "ghana": {"m":"ghanés","f":"ghanesa"},
  "gibraltar": {"m":"gibraltareño","f":"gibraltareña"},
  "gozo": {"m":"gozitano","f":"gozitana"},
  "granada": {"m":"granadino","f":"granadina"},
  "grecia": {"m":"griego","f":"griega"},
  "groenlandia": {"m":"groenlandés","f":"groenlandesa"},
  "guadalupe": {"m":"guadalupeño","f":"guadalupeña"},
  "guam": {"m":"guameño","f":"guameña"},
  "guatemala": {"m":"guatemalteco","f":"guatemalteca"},
  "guayana francesa": {"m":"francoguayanés","f":"francoguayanesa"},
  "guernsey": {"m":"guerneseyés","f":"guerneseyesa"},
  "guinea": {"m":"guineano","f":"guineana"},
  "guinea ecuatorial": {"m":"ecuatoguineano","f":"ecuatoguineana"},
  "guineabisau": {"m":"bisauguineano","f":"bisauguineana"},
  "guyana": {"m":"guyanés","f":"guyanesa"},
  "haiti": {"m":"haitiano","f":"haitiana"},
  "honduras": {"m":"hondureño","f":"hondureña"},
  "hong kong": {"m":"hongkonés","f":"hongkonesa"},
  "hungria": {"m":"húngaro","f":"húngara"},
  "india": {"m":"indio","f":"india"},
  "indonesia": {"m":"indonesio","f":"indonesia"},
  "inglaterra": {"m":"inglés","f":"inglesa"},
  "irak": {"m":"iraquí","f":"iraquí"},
  "iran": {"m":"iraní","f":"iraní"},
  "irlanda": {"m":"irlandés","f":"irlandesa"},
  "irlanda del norte": {"m":"norirlandés","f":"norirlandesa"},
  "isla de man": {"m":"manés","f":"manesa"},
  "isla de navidad": {"m":"navideño","f":"navideña"},
  "isla norfolk": {"m":"norfolkense","f":"norfolkense"},
  "islandia": {"m":"islandés","f":"islandesa"},
  "islas baleares": {"m":"balear","f":"balear"},
  "islas caiman": {"m":"caimanés","f":"caimanesa"},
  "islas cocos": {"m":"cocano","f":"cocana"},
  "islas cook": {"m":"cookiano","f":"cookiana"},
  "islas feroe": {"m":"feroés","f":"feroesa"},
  "islas malvinas": {"m":"malvinense","f":"malvinense"},
  "islas marianas del norte": {"m":"chamorro","f":"chamorra"},
  "islas marshall": {"m":"marshalés","f":"marshalesa"},
  "islas pitcairn": {"m":"pitcairnés","f":"pitcairnesa"},
  "islas salomon": {"m":"salomonense","f":"salomonense"},
  "islas turcas y caicos": {"m":"turcocaiqueño","f":"turcocaiqueña"},
  "islas virgenes britanicas": {"m":"virgenense británico","f":"virgenense británica"},
  "islas virgenes de los estados unidos": {"m":"virgenense estadounidense","f":"virgenense estadounidense"},
  "israel": {"m":"israelí","f":"israelí"},
  "italia": {"m":"italiano","f":"italiana"},
  "jamaica": {"m":"jamaicano","f":"jamaicana"},
  "japon": {"m":"japonés","f":"japonesa"},
  "jersey": {"m":"jerseyés","f":"jerseyesa"},
  "jordania": {"m":"jordano","f":"jordana"},
  "kazajistan": {"m":"kazajo","f":"kazaja"},
  "kenia": {"m":"keniano","f":"keniana"},
  "kirguistan": {"m":"kirguís","f":"kirguís"},
  "kiribati": {"m":"kiribatiano","f":"kiribatiana"},
  "kosovo": {"m":"kosovar","f":"kosovar"},
  "kuwait": {"m":"kuwaití","f":"kuwaití"},
  "la rioja": {"m":"riojano","f":"riojana"},
  "laos": {"m":"laosiano","f":"laosiana"},
  "lesoto": {"m":"lesotense","f":"lesotense"},
  "letonia": {"m":"letón","f":"letona"},
  "libano": {"m":"libanés","f":"libanesa"},
  "liberia": {"m":"liberiano","f":"liberiana"},
  "libia": {"m":"libio","f":"libia"},
  "liechtenstein": {"m":"liechtensteiniano","f":"liechtensteiniana"},
  "lituania": {"m":"lituano","f":"lituana"},
  "luxemburgo": {"m":"luxemburgués","f":"luxemburguesa"},
  "macao": {"m":"macaense","f":"macaense"},
  "macedonia del norte": {"m":"macedonio","f":"macedonia"},
  "madagascar": {"m":"malgache","f":"malgache"},
  "malasia": {"m":"malasio","f":"malasia"},
  "malaui": {"m":"malauí","f":"malauí"},
  "maldivas": {"m":"maldivo","f":"maldiva"},
  "mali": {"m":"maliense","f":"maliense"},
  "malta": {"m":"maltés","f":"maltesa"},
  "marruecos": {"m":"marroquí","f":"marroquí"},
  "martinica": {"m":"martiniqués","f":"martiniquesa"},
  "mauricio": {"m":"mauriciano","f":"mauriciana"},
  "mauritania": {"m":"mauritano","f":"mauritana"},
  "mayotte": {"m":"mayotés","f":"mayotesa"},
  "melilla": {"m":"melillense","f":"melillense"},
  "mexico": {"m":"mexicano","f":"mexicana"},
  "moldavia": {"m":"moldavo","f":"moldava"},
  "monaco": {"m":"monegasco","f":"monegasca"},
  "mongolia": {"m":"mongol","f":"mongola"},
  "montenegro": {"m":"montenegrino","f":"montenegrina"},
  "montserrat": {"m":"monserratino","f":"monserratina"},
  "mozambique": {"m":"mozambiqueño","f":"mozambiqueña"},
  "namibia": {"m":"namibio","f":"namibia"},
  "nauru": {"m":"nauruano","f":"nauruana"},
  "navarra": {"m":"navarro","f":"navarra"},
  "nepal": {"m":"nepalés","f":"nepalesa"},
  "nicaragua": {"m":"nicaragüense","f":"nicaragüense"},
  "niger": {"m":"nigerino","f":"nigerina"},
  "nigeria": {"m":"nigeriano","f":"nigeriana"},
  "niue": {"m":"niueño","f":"niueña"},
  "noruega": {"m":"noruego","f":"noruega"},
  "nueva caledonia": {"m":"neocaledonio","f":"neocaledonia"},
  "nueva zelanda": {"m":"neozelandés","f":"neozelandesa"},
  "oman": {"m":"omaní","f":"omaní"},
  "osetia del sur": {"m":"surosetio","f":"surosetia"},
  "pais vasco": {"m":"vasco","f":"vasca"},
  "paises bajos": {"m":"neerlandés","f":"neerlandesa"},
  "pakistan": {"m":"pakistaní","f":"pakistaní"},
  "palaos": {"m":"palauano","f":"palauana"},
  "palestina": {"m":"palestino","f":"palestina"},
  "panama": {"m":"panameño","f":"panameña"},
  "papua nueva guinea": {"m":"papú","f":"papú"},
  "paraguay": {"m":"paraguayo","f":"paraguaya"},
  "peru": {"m":"peruano","f":"peruana"},
  "polonia": {"m":"polaco","f":"polaca"},
  "portugal": {"m":"portugués","f":"portuguesa"},
  "puerto rico": {"m":"puertorriqueño","f":"puertorriqueña"},
  "region de murcia": {"m":"murciano","f":"murciana"},
  "reino unido": {"m":"británico","f":"británica"},
  "republica arabe saharaui democratica": {"m":"saharaui","f":"saharaui"},
  "republica centroafricana": {"m":"centroafricano","f":"centroafricana"},
  "republica checa": {"m":"checo","f":"checa"},
  "republica del congo": {"m":"congoleño","f":"congoleña"},
  "republica democratica del congo": {"m":"congoleño","f":"congoleña"},
  "republica dominicana": {"m":"dominicano","f":"dominicana"},
  "reunion": {"m":"reunionés","f":"reunionesa"},
  "ruanda": {"m":"ruandés","f":"ruandesa"},
  "rumania": {"m":"rumano","f":"rumana"},
  "rusia": {"m":"ruso","f":"rusa"},
  "sahara occidental": {"m":"saharaui","f":"saharaui"},
  "samoa": {"m":"samoano","f":"samoana"},
  "samoa americana": {"m":"samoamericano","f":"samoamericana"},
  "san bartolome": {"m":"sanbartolomeano","f":"sanbartolomeana"},
  "san cristobal y nieves": {"m":"sancristobaleño","f":"sancristobaleña"},
  "san marino": {"m":"sanmarinense","f":"sanmarinense"},
  "san martin": {"m":"sanmartitense","f":"sanmartitense"},
  "san pedro y miquelon": {"m":"sanpedrino","f":"sanpedrina"},
  "san vicente y las granadinas": {"m":"sanvicentino","f":"sanvicentina"},
  "santa elena, ascension y tristan de acuna": {"m":"santaheleno","f":"santahelena"},
  "santa lucia": {"m":"santalucense","f":"santalucense"},
  "santo tome y principe": {"m":"santotomense","f":"santotomense"},
  "senegal": {"m":"senegalés","f":"senegalesa"},
  "serbia": {"m":"serbio","f":"serbia"},
  "seychelles": {"m":"seychellense","f":"seychellense"},
  "sierra leona": {"m":"sierraleonés","f":"sierraleonesa"},
  "singapur": {"m":"singapurense","f":"singapurense"},
  "sint maarten": {"m":"sanmartitense","f":"sanmartitense"},
  "siria": {"m":"sirio","f":"siria"},
  "somalia": {"m":"somalí","f":"somalí"},
  "somalilandia": {"m":"somalilandés","f":"somalilandesa"},
  "sri lanka": {"m":"esrilanqués","f":"esrilanquesa"},
  "suazilandia": {"m":"suazi","f":"suazi"},
  "sudafrica": {"m":"sudafricano","f":"sudafricana"},
  "sudan": {"m":"sudanés","f":"sudanesa"},
  "sudan del sur": {"m":"sursudanés","f":"sursudanesa"},
  "suecia": {"m":"sueco","f":"sueca"},
  "suiza": {"m":"suizo","f":"suiza"},
  "surinam": {"m":"surinamés","f":"surinamesa"},
  "svalbard y jan mayen": {"m":"svalbarense","f":"svalbarense"},
  "tahiti": {"m":"tahitiano","f":"tahitiana"},
  "tailandia": {"m":"tailandés","f":"tailandesa"},
  "taiwan": {"m":"taiwanés","f":"taiwanesa"},
  "tanzania": {"m":"tanzano","f":"tanzana"},
  "tayikistan": {"m":"tayiko","f":"tayika"},
  "timorleste": {"m":"timorense","f":"timorense"},
  "togo": {"m":"togolés","f":"togolesa"},
  "tokelau": {"m":"tokelauense","f":"tokelauense"},
  "tonga": {"m":"tongano","f":"tongana"},
  "transnistria": {"m":"transnistrio","f":"transnistria"},
  "trinidad y tobago": {"m":"trinitense","f":"trinitense"},
  "tunez": {"m":"tunecino","f":"tunecina"},
  "turkmenistan": {"m":"turcomano","f":"turcomana"},
  "turquia": {"m":"turco","f":"turca"},
  "tuvalu": {"m":"tuvaluano","f":"tuvaluana"},
  "ucrania": {"m":"ucraniano","f":"ucraniana"},
  "uganda": {"m":"ugandés","f":"ugandesa"},
  "uruguay": {"m":"uruguayo","f":"uruguaya"},
  "uzbekistan": {"m":"uzbeko","f":"uzbeka"},
  "vanuatu": {"m":"vanuatuense","f":"vanuatuense"},
  "venezuela": {"m":"venezolano","f":"venezolana"},
  "vietnam": {"m":"vietnamita","f":"vietnamita"},
  "wallis y futuna": {"m":"walisiano","f":"walisiana"},
  "yemen": {"m":"yemení","f":"yemení"},
  "yibuti": {"m":"yibutiano","f":"yibutiana"},
  "zambia": {"m":"zambiano","f":"zambiana"},
  "zanzibar": {"m":"zanzibarí","f":"zanzibarí"},
  "zimbabue": {"m":"zimbabuense","f":"zimbabuense"}
};
