/* =========================================================
   COPA MANAGER 2026 — datos/paises-iso.js
   Mapeo de países -> código ISO 3166-1 alpha-2 (minúscula) para elegir su bandera.
   Banderas: repo irixapps/World-Flags (png1024, 1024x683 (3:2)), incluidas en la carpeta FLAG_BASE.
   BY_NAME está normalizado con normLoose; BY_FIFA usa el código FIFA (respaldo ante renombres).
   Reino Unido: el repo no trae banderas separadas de Inglaterra/Escocia/Gales/Irlanda del Norte;
   se mapean a eng/sco/wal/nir y, si el archivo no existe, la imagen se oculta sola (onerror).
   Cargar después de datos/constantes.js.
   ========================================================= */
const FLAG_BASE = "banderas/";
const COUNTRY_ISO_BY_NAME = {
  "afganistan": "af",
  "aland": "ax",
  "aland, islas": "ax",
  "albania": "al",
  "alemania": "de",
  "andorra": "ad",
  "angola": "ao",
  "anguila": "ai",
  "antartida": "aq",
  "antigua y barbuda": "ag",
  "arabia saudita": "sa",
  "argelia": "dz",
  "argentina": "ar",
  "armenia": "am",
  "aruba": "aw",
  "australia": "au",
  "austria": "at",
  "azerbaiyan": "az",
  "bahamas": "bs",
  "bahamas (las)": "bs",
  "banglades": "bd",
  "barbados": "bb",
  "barein": "bh",
  "belarus": "by",
  "belgica": "be",
  "belice": "bz",
  "benin": "bj",
  "bermuda": "bm",
  "bermudas": "bm",
  "bhutan": "bt",
  "bielorrusia": "by",
  "birmania": "mm",
  "bolivia": "bo",
  "bolivia (estado plurinacional de)": "bo",
  "bonaire": "bq",
  "bonaire, san eustaquio y saba": "bq",
  "bosnia y herzegovina": "ba",
  "botsuana": "bw",
  "bouvet, isla": "bv",
  "brasil": "br",
  "brunei": "bn",
  "brunei darussalam": "bn",
  "bulgaria": "bg",
  "burkina faso": "bf",
  "burundi": "bi",
  "butan": "bt",
  "cabo verde": "cv",
  "caiman, (las) islas": "ky",
  "caiman, islas": "ky",
  "camboya": "kh",
  "camerun": "cm",
  "canada": "ca",
  "catar": "qa",
  "chad": "td",
  "chequia": "cz",
  "chile": "cl",
  "china": "cn",
  "chipre": "cy",
  "christmas, isla": "cx",
  "ciudad del vaticano": "va",
  "cocos / keeling, (las) islas": "cc",
  "cocos / keeling, islas": "cc",
  "colombia": "co",
  "comoras": "km",
  "comoras (las)": "km",
  "congo": "cd",
  "congo (el)": "cg",
  "congo (la republica democratica del)": "cd",
  "cook, islas": "ck",
  "corea": "kp",
  "corea (la republica de)": "kr",
  "corea (la republica popular democratica de)": "kp",
  "corea del norte": "kp",
  "corea del sur": "kr",
  "costa de marfil": "ci",
  "costa rica": "cr",
  "cote divoire": "ci",
  "croacia": "hr",
  "cuba": "cu",
  "curazao": "cw",
  "dinamarca": "dk",
  "dominica": "dm",
  "dominicana, (la) republica": "do",
  "dominicana, republica": "do",
  "eau": "ae",
  "ecuador": "ec",
  "egipto": "eg",
  "el congo": "cg",
  "el niger": "ne",
  "el reino unido de gran bretana e irlanda del norte": "gb",
  "el salvador": "sv",
  "el sudan": "sd",
  "el territorio britanico del oceano indico": "io",
  "emiratos arabes unidos": "ae",
  "emiratos arabes unidos (los)": "ae",
  "eritrea": "er",
  "escocia": "sco",
  "eslovaquia": "sk",
  "eslovenia": "si",
  "espana": "es",
  "estado plurinacional de bolivia": "bo",
  "estados federados de micronesia": "fm",
  "estados unidos": "us",
  "estados unidos de america": "us",
  "estados unidos de america (los)": "us",
  "estonia": "ee",
  "esuatini": "sz",
  "etiopia": "et",
  "feroe, (las) islas": "fo",
  "feroe, islas": "fo",
  "filipinas": "ph",
  "filipinas (las)": "ph",
  "finlandia": "fi",
  "fiyi": "fj",
  "francia": "fr",
  "gabon": "ga",
  "gales": "wal",
  "gambia": "gm",
  "gambia (la)": "gm",
  "georgia": "ge",
  "georgia del sur (la) y las islas sandwich del sur": "gs",
  "georgia del sur y las islas sandwich del sur": "gs",
  "ghana": "gh",
  "gibraltar": "gi",
  "granada": "gd",
  "grecia": "gr",
  "groenlandia": "gl",
  "guadalupe": "gp",
  "guam": "gu",
  "guatemala": "gt",
  "guayana francesa": "gf",
  "guernsey": "gg",
  "guinea": "gn",
  "guinea bissau": "gw",
  "guinea ecuatorial": "gq",
  "guineabisau": "gw",
  "guineabissau": "gw",
  "guyana": "gy",
  "haiti": "ht",
  "honduras": "hn",
  "hong kong": "hk",
  "hungria": "hu",
  "india": "in",
  "indonesia": "id",
  "inglaterra": "eng",
  "irak": "iq",
  "iran": "ir",
  "iran (republica islamica de)": "ir",
  "irlanda": "ie",
  "irlanda del norte": "nir",
  "isla de man": "im",
  "islandia": "is",
  "islas caiman": "ky",
  "islas cook": "ck",
  "islas feroe": "fo",
  "islas malvinas": "fk",
  "islas marianas del norte": "mp",
  "islas marshall": "mh",
  "islas menores alejadas de estados unidos": "um",
  "islas salomon": "sb",
  "islas turcas y caicos": "tc",
  "islas virgenes britanicas": "vg",
  "islas virgenes de los estados unidos": "vi",
  "israel": "il",
  "italia": "it",
  "jamaica": "jm",
  "japon": "jp",
  "jersey": "je",
  "jordania": "jo",
  "kazajistan": "kz",
  "kenia": "ke",
  "kirguistan": "kg",
  "kiribati": "ki",
  "kuwait": "kw",
  "la gambia": "gm",
  "la republica centroafricana": "cf",
  "la republica de corea": "kr",
  "la republica de moldavia": "md",
  "la republica democratica del congo": "cd",
  "la republica popular democratica de corea": "kp",
  "la santa sede": "va",
  "lao, (la) republica democratica popular": "la",
  "lao, republica democratica popular": "la",
  "laos": "la",
  "las bahamas": "bs",
  "las comoras": "km",
  "las filipinas": "ph",
  "las tierras australes francesas": "tf",
  "lesoto": "ls",
  "letonia": "lv",
  "libano": "lb",
  "liberia": "lr",
  "libia": "ly",
  "liechtenstein": "li",
  "lituania": "lt",
  "los emiratos arabes unidos": "ae",
  "los estados unidos de america": "us",
  "los paises bajos": "nl",
  "luxemburgo": "lu",
  "macao": "mo",
  "macedonia del norte": "mk",
  "madagascar": "mg",
  "malasia": "my",
  "malaui": "mw",
  "maldivas": "mv",
  "mali": "ml",
  "malta": "mt",
  "malvinas [falkland], (las) islas": "fk",
  "malvinas [falkland], islas": "fk",
  "marianas septentrionales, (las) islas": "mp",
  "marianas septentrionales, islas": "mp",
  "marruecos": "ma",
  "marshall, (las) islas": "mh",
  "marshall, islas": "mh",
  "martinica": "mq",
  "mauricio": "mu",
  "mauritania": "mr",
  "mayotte": "yt",
  "mexico": "mx",
  "micronesia": "fm",
  "micronesia (estados federados de)": "fm",
  "moldavia": "md",
  "moldavia (la republica de)": "md",
  "monaco": "mc",
  "mongolia": "mn",
  "montenegro": "me",
  "montserrat": "ms",
  "mozambique": "mz",
  "myanmar": "mm",
  "namibia": "na",
  "nauru": "nr",
  "nepal": "np",
  "nicaragua": "ni",
  "niger": "ne",
  "niger (el)": "ne",
  "nigeria": "ng",
  "niue": "nu",
  "norfolk, isla": "nf",
  "noruega": "no",
  "nueva caledonia": "nc",
  "nueva zelanda": "nz",
  "nueva zelandia": "nz",
  "oman": "om",
  "paises bajos": "nl",
  "paises bajos (los)": "nl",
  "pakistan": "pk",
  "palaos": "pw",
  "palestina": "ps",
  "palestina, estado de": "ps",
  "panama": "pa",
  "papua nueva guinea": "pg",
  "paraguay": "py",
  "parte francesa san martin": "mf",
  "parte neerlandesa san martin": "sx",
  "peru": "pe",
  "pitcairn": "pn",
  "polinesia francesa": "pf",
  "polonia": "pl",
  "portugal": "pt",
  "provincia de china taiwan": "tw",
  "puerto rico": "pr",
  "rd congo": "cd",
  "reino unido de gran bretana e irlanda del norte": "gb",
  "reino unido de gran bretana e irlanda del norte (el)": "gb",
  "republica arabe siria": "sy",
  "republica bolivariana de venezuela": "ve",
  "republica centroafricana": "cf",
  "republica centroafricana (la)": "cf",
  "republica checa": "cz",
  "republica del congo": "cg",
  "republica democratica del congo": "cd",
  "republica dominicana": "do",
  "republica islamica de iran": "ir",
  "reunion": "re",
  "ruanda": "rw",
  "rumania": "ro",
  "rusia": "ru",
  "rusia, (la) federacion de": "ru",
  "rusia, federacion de": "ru",
  "sahara occidental": "eh",
  "saint kitts y nevis": "kn",
  "salomon, islas": "sb",
  "samoa": "ws",
  "samoa americana": "as",
  "san barthelemy": "bl",
  "san bartolome": "bl",
  "san cristobal y nieves": "kn",
  "san marino": "sm",
  "san martin": "mf",
  "san martin (parte francesa)": "mf",
  "san martin (parte neerlandesa)": "sx",
  "san pedro y miquelon": "pm",
  "san vicente y las granadinas": "vc",
  "santa elena, ascension y tristan de acuna": "sh",
  "santa lucia": "lc",
  "santa sede": "va",
  "santa sede (la)": "va",
  "santo tome y principe": "st",
  "senegal": "sn",
  "serbia": "rs",
  "seychelles": "sc",
  "sierra leona": "sl",
  "singapur": "sg",
  "sint maarten": "sx",
  "siria": "sy",
  "somalia": "so",
  "sri lanka": "lk",
  "suazilandia": "sz",
  "sudafrica": "za",
  "sudan": "sd",
  "sudan (el)": "sd",
  "sudan del sur": "ss",
  "suecia": "se",
  "suiza": "ch",
  "surinam": "sr",
  "suriname": "sr",
  "svalbard y jan mayen": "sj",
  "tahiti": "pf",
  "tailandia": "th",
  "taiwan": "tw",
  "taiwan (provincia de china)": "tw",
  "tanzania": "tz",
  "tanzania, republica unida de": "tz",
  "tayikistan": "tj",
  "territorio britanico del oceano indico": "io",
  "territorio britanico del oceano indico (el)": "io",
  "tierras australes francesas": "tf",
  "tierras australes francesas (las)": "tf",
  "timorleste": "tl",
  "togo": "tg",
  "tokelau": "tk",
  "tonga": "to",
  "trinidad y tabago": "tt",
  "trinidad y tobago": "tt",
  "tunez": "tn",
  "turcas y caicos, (las) islas": "tc",
  "turcas y caicos, islas": "tc",
  "turkmenistan": "tm",
  "turquia": "tr",
  "tuvalu": "tv",
  "ucrania": "ua",
  "uganda": "ug",
  "uruguay": "uy",
  "uzbekistan": "uz",
  "vanuatu": "vu",
  "venezuela": "ve",
  "venezuela (republica bolivariana de)": "ve",
  "viet nam": "vn",
  "vietnam": "vn",
  "virgenes britanicas, islas": "vg",
  "virgenes de los estados unidos, islas": "vi",
  "wallis y futuna": "wf",
  "yemen": "ye",
  "yibuti": "dj",
  "zambia": "zm",
  "zimbabue": "zw",
  "zimbabue|": "zw"
};
const COUNTRY_ISO_BY_FIFA = {
  "AFG": "af",
  "AIA": "ai",
  "ALA": "ax",
  "ALB": "al",
  "ALG": "dz",
  "AND": "ad",
  "ANG": "ao",
  "ARG": "ar",
  "ARM": "am",
  "ARU": "aw",
  "ASA": "as",
  "ATG": "ag",
  "AUS": "au",
  "AUT": "at",
  "AZE": "az",
  "BAH": "bs",
  "BAN": "bd",
  "BDI": "bi",
  "BEL": "be",
  "BEN": "bj",
  "BER": "bm",
  "BFA": "bf",
  "BHR": "bh",
  "BHU": "bt",
  "BIH": "ba",
  "BLM": "bl",
  "BLR": "by",
  "BLZ": "bz",
  "BOL": "bo",
  "BON": "bq",
  "BOT": "bw",
  "BRA": "br",
  "BRB": "bb",
  "BRU": "bn",
  "BUL": "bg",
  "BUR": "mm",
  "CAM": "kh",
  "CAN": "ca",
  "CAY": "ky",
  "CGO": "cg",
  "CHA": "td",
  "CHI": "cl",
  "CHN": "cn",
  "CIV": "ci",
  "CMR": "cm",
  "COD": "cd",
  "COK": "ck",
  "COL": "co",
  "COM": "km",
  "CPV": "cv",
  "CRC": "cr",
  "CRO": "hr",
  "CTA": "cf",
  "CUB": "cu",
  "CUW": "cw",
  "CYP": "cy",
  "CZE": "cz",
  "DEN": "dk",
  "DJI": "dj",
  "DMA": "dm",
  "DOM": "do",
  "ECU": "ec",
  "EGY": "eg",
  "ENG": "eng",
  "EQG": "gq",
  "ERI": "er",
  "ESP": "es",
  "EST": "ee",
  "ETH": "et",
  "FIJ": "fj",
  "FIN": "fi",
  "FIS": "fk",
  "FRA": "fr",
  "FRO": "fo",
  "GAB": "ga",
  "GAM": "gm",
  "GEO": "ge",
  "GER": "de",
  "GGY": "gg",
  "GHA": "gh",
  "GIB": "gi",
  "GLP": "gp",
  "GNB": "gw",
  "GRE": "gr",
  "GRL": "gl",
  "GRN": "gd",
  "GUA": "gt",
  "GUF": "gf",
  "GUI": "gn",
  "GUM": "gu",
  "GUY": "gy",
  "HAI": "ht",
  "HKG": "hk",
  "HON": "hn",
  "HUN": "hu",
  "IDN": "id",
  "IND": "in",
  "IOM": "im",
  "IRL": "ie",
  "IRN": "ir",
  "IRQ": "iq",
  "ISL": "is",
  "ISR": "il",
  "ITA": "it",
  "JAM": "jm",
  "JER": "je",
  "JOR": "jo",
  "JPN": "jp",
  "KAZ": "kz",
  "KEN": "ke",
  "KGZ": "kg",
  "KIR": "ki",
  "KOR": "kr",
  "KSA": "sa",
  "KUW": "kw",
  "LAO": "la",
  "LBN": "lb",
  "LBR": "lr",
  "LBY": "ly",
  "LCA": "lc",
  "LES": "ls",
  "LIE": "li",
  "LTU": "lt",
  "LUX": "lu",
  "LVA": "lv",
  "MAC": "mo",
  "MAD": "mg",
  "MAR": "ma",
  "MAS": "my",
  "MDA": "md",
  "MDV": "mv",
  "MEX": "mx",
  "MKD": "mk",
  "MLI": "ml",
  "MLT": "mt",
  "MNE": "me",
  "MNG": "mn",
  "MNP": "mp",
  "MOZ": "mz",
  "MRI": "mu",
  "MSR": "ms",
  "MTN": "mr",
  "MTQ": "mq",
  "MWI": "mw",
  "MYA": "mm",
  "NAM": "na",
  "NCA": "ni",
  "NCL": "nc",
  "NED": "nl",
  "NEP": "np",
  "NGA": "ng",
  "NIG": "ne",
  "NIR": "nir",
  "NIU": "nu",
  "NOR": "no",
  "NZL": "nz",
  "OMA": "om",
  "PAK": "pk",
  "PAN": "pa",
  "PAR": "py",
  "PER": "pe",
  "PHI": "ph",
  "PLE": "ps",
  "PNG": "pg",
  "POL": "pl",
  "POR": "pt",
  "PRK": "kp",
  "PUR": "pr",
  "QAT": "qa",
  "REU": "re",
  "ROU": "ro",
  "RSA": "za",
  "RUS": "ru",
  "RWA": "rw",
  "SAM": "ws",
  "SCO": "sco",
  "SDN": "sd",
  "SEN": "sn",
  "SEY": "sc",
  "SGP": "sg",
  "SHN": "sh",
  "SKN": "kn",
  "SLE": "sl",
  "SLV": "sv",
  "SMN": "mf",
  "SMR": "sm",
  "SOL": "sb",
  "SOM": "so",
  "SPM": "pm",
  "SRB": "rs",
  "SRI": "lk",
  "SSD": "ss",
  "STP": "st",
  "SUI": "ch",
  "SUR": "sr",
  "SVK": "sk",
  "SVN": "si",
  "SWE": "se",
  "SWZ": "sz",
  "SXM": "sx",
  "SYR": "sy",
  "TAH": "pf",
  "TAN": "tz",
  "TCA": "tc",
  "TGA": "to",
  "THA": "th",
  "TJK": "tj",
  "TKM": "tm",
  "TLS": "tl",
  "TOG": "tg",
  "TOK": "tk",
  "TPE": "tw",
  "TRI": "tt",
  "TUN": "tn",
  "TUR": "tr",
  "TUV": "tv",
  "UAE": "ae",
  "UGA": "ug",
  "UKR": "ua",
  "URU": "uy",
  "USA": "us",
  "UZB": "uz",
  "VAN": "vu",
  "VAT": "va",
  "VEN": "ve",
  "VGB": "vg",
  "VIE": "vn",
  "VIN": "vc",
  "VIR": "vi",
  "WAL": "wal",
  "WLF": "wf",
  "WSH": "eh",
  "YEM": "ye",
  "ZAM": "zm",
  "ZIM": "zw"
};

// Código ISO (minúscula) de un país dado su objeto {commonName,fifaCode,iso} o su nombre. Prioriza el
// iso ya guardado, luego el código FIFA, luego el nombre normalizado. Devuelve null si no hay bandera.
function countryIsoCode(x){
  if(!x) return null;
  if(typeof x === "object"){
    if(x.iso) return x.iso;
    if(x.fifaCode && COUNTRY_ISO_BY_FIFA[x.fifaCode.toUpperCase()]) return COUNTRY_ISO_BY_FIFA[x.fifaCode.toUpperCase()];
    x = x.commonName;
  }
  return COUNTRY_ISO_BY_NAME[normLoose(x)] || null;
}
// URL/base64 de la bandera de un país (objeto o nombre). Prioriza la bandera SUBIDA MANUALMENTE
// (country.flagImg, base64, igual que los logos de club), luego el archivo por código ISO. null si no hay.
// Índice memoizado de países por nombre (normLoose) y por código FIFA, para que flagSrc no recorra
// DB.countries en cada llamada (en listas grandes se llamaba una vez por fila -> coste cuadrático).
// Se invalida al editar países o al recargar/importar la base (invalidateCountryIndex).
let _countryIdxCache = null;
function _countryIndex(){
  if(_countryIdxCache) return _countryIdxCache;
  const byName = Object.create(null), byFifa = Object.create(null);
  (DB.countries||[]).forEach(c=>{
    if(c.commonName) byName[normLoose(c.commonName)] = c;
    if(c.fifaCode) byFifa[c.fifaCode.toUpperCase()] = c;
  });
  _countryIdxCache = { byName, byFifa };
  return _countryIdxCache;
}
function invalidateCountryIndex(){ _countryIdxCache = null; }

// --- Deduplicación de imágenes base64 por render (banderas y logos) ---
// Una misma imagen base64 (bandera de Inglaterra, escudo de un club) se repetía incrustada en cada
// fila de una lista grande (p. ej. 26 jugadores => 26 copias del mismo base64 = MBs de HTML). En su
// lugar registramos cada base64 una sola vez por render y las filas la referencian por clase CSS
// (background-image). render() llama a beginFlagDedup() antes de construir la vista y antepone
// flushFlagDedupStyle() al HTML. El registro es genérico: lo usan flagIconHTML/flagBadgeHTML y
// teamLogoIconHTML/clubLogoIconHTML.
let _flagDyn = null;
function beginFlagDedup(){ _flagDyn = { map:new Map(), css:[] }; }
function flushFlagDedupStyle(){
  const d = _flagDyn; _flagDyn = null;
  if(!d || !d.css.length) return "";
  return `<style data-flag-dyn>${d.css.join("")}</style>`;
}
function _flagDedupClass(dataUri){
  if(!_flagDyn) return null;
  let id = _flagDyn.map.get(dataUri);
  if(id===undefined){
    id = _flagDyn.map.size;
    _flagDyn.map.set(dataUri, id);
    _flagDyn.css.push(`.fdyn-${id}{background-image:url("${dataUri}")}`);
  }
  return `fdyn-${id}`;
}

function flagSrc(x){
  if(!x) return null;
  let name = null, fifa = null, isoCand = null;
  if(typeof x === "object"){
    if(x.flagImg) return x.flagImg;                 // país con bandera manual
    name = x.commonName; fifa = x.fifaCode; isoCand = x.iso;
  } else { name = x; }
  const idx = _countryIndex();
  const co = (fifa && idx.byFifa[fifa.toUpperCase()]) || (name && idx.byName[normLoose(name)]) || null;
  if(co && co.flagImg) return co.flagImg;
  if(co && !isoCand) isoCand = co.iso;
  const iso = isoCand
    || (name ? COUNTRY_ISO_BY_NAME[normLoose(name)] : null)
    || (fifa ? COUNTRY_ISO_BY_FIFA[fifa.toUpperCase()] : null);
  return iso ? (FLAG_BASE + iso + ".png") : null;
}
// <img> de bandera para meter dentro de una etiqueta, a la izquierda del nombre. "" si no hay bandera.
// Si el archivo falta (p. ej. Inglaterra sin subir), la imagen se oculta sola.
// Bandera de un país/selección. Si no hay archivo (países extintos, sin ISO) se emite igual un hueco
// del mismo tamaño para que el texto de las listas quede alineado con el de las filas que sí tienen
// bandera. Por lo mismo, si la imagen falla al cargar se oculta con visibility (que conserva el
// espacio) y no con display:none (que lo colapsa y descuadra la fila).
function flagIconHTML(x){
  const src = flagSrc(x);
  if(!src) return flagSpacerHTML();
  return `<img class="flag-ic" src="${src}" alt="" loading="lazy" onerror="this.style.visibility='hidden'">`;
}
function flagSpacerHTML(){ return `<span class="flag-ic flag-ic-empty" aria-hidden="true"></span>`; }
// Bandera dentro de una etiqueta (badge) del mismo alto que las demás (conf, nº jugadores).
function flagBadgeHTML(x){
  const src = flagSrc(x);
  if(!src) return "";
  return `<span class="badge flag-badge"><img src="${src}" alt="" loading="lazy" onerror="this.parentElement.style.display='none'"></span>`;
}
// Logo inline (selección o club) para meter a la izquierda de un nombre. "" si no hay logo subido.
// Escudo genérico para selecciones y clubes sin logo propio: se pinta exactamente igual que un logo
// real, con un <img> apuntando a la misma imagen para todos. Antes se recoloreaba con los colores de
// cada equipo, lo que obligaba a procesar cada escudo en un canvas y hacía lenta la apertura de las
// listas grandes; como los logos genéricos se van a ir sustituyendo por los reales, no compensaba.
function defaultCrestIconHTML(){
  return `<img class="logo-ic" src="${DEFAULT_CREST_SRC}" alt="" loading="lazy" onerror="this.style.visibility='hidden'">`;
}
// Versión grande (fichas y listas), dentro de la caja .crest-mini.
function defaultCrestBoxHTML(entity, extraStyle){
  return `<div class="crest-mini has-img" style="${extraStyle||''}"><img src="${DEFAULT_CREST_SRC}" alt="" loading="lazy" onerror="this.style.visibility='hidden'"></div>`;
}

function teamLogoIconHTML(team){
  if(!team) return "";
  return team.logoImg
    ? `<img class="logo-ic" src="${team.logoImg}" alt="" loading="lazy" onerror="this.style.visibility='hidden'">`
    : defaultCrestIconHTML();
}
function clubLogoIconHTML(club){
  if(!club) return "";
  return club.logoImg
    ? `<img class="logo-ic" src="${club.logoImg}" alt="" loading="lazy" onerror="this.style.visibility='hidden'">`
    : defaultCrestIconHTML();
}
